In [3]:
#Q1
import numpy as np
arr=np.empty([10],dtype=int)
arr.fill(5)
print(arr)
print("\n")

#Q2
arr=np.arange(10,51)
print(arr)
print("\n")

#Q3
arr=np.arange(10,51,2,dtype=int)
print(arr)
print("\n")

#Q4
arr=np.arange(0,9).reshape(3,3)
print(arr)
print("\n")

#Q5
arr=np.random.rand(25)
print(arr)
print("\n")

#Q6
arr=np.arange(0,1.01,0.01)
print(arr)
print("\n")

#Q7
arr=np.linspace(0,1,20)
print(arr)
print("\n")

#Q8
arr1=np.arange(1,26).reshape(5,5)
print(arr1)
mat=arr1[2: , 1:]
print("\n\n")
print(mat)

arr2=arr1[0:3,1:2]
print("\n\n")
print(arr2)

print("\n")
print("Sum of all elements is")
total_sum=np.sum(mat)
print(total_sum)
print("\n")
print("Sum of all columns ")
sum_of_row=np.sum(mat,axis=0)
print(sum_of_row)
print("\n")

print("Sum of all rows is")
sum_of_columns=np.sum(mat,axis=1)
print(sum_of_columns)

[5 5 5 5 5 5 5 5 5 5]


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[0.99585926 0.02415979 0.00814866 0.31295112 0.14445191 0.45004315
 0.11121517 0.30507342 0.54406839 0.95323421 0.7174589  0.03370569
 0.97963759 0.39561739 0.17333557 0.13261297 0.57931083 0.10192675
 0.71560567 0.64774697 0.40999364 0.26577554 0.56368547 0.30233841
 0.00300589]


[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0